import { useEffect, useRef } from "react";
import * as maplibregl from "maplibre-gl";
import { type GeoJSONSource, type Map as MapLibreMap, type MapLayerMouseEvent } from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import { mapStyle } from "./mapStyle";
import type { MapHelpPoint, MapRoute } from "./mapTypes";

const routeFeature = (route: MapRoute) => ({ type: "Feature" as const, properties: { id: route.id, context: route.context }, geometry: { type: "LineString" as const, coordinates: route.coordinates } });
const collection = (features: ReturnType<typeof routeFeature>[]) => ({ type: "FeatureCollection" as const, features });

export function SaferPathMap({ routes, selectedRoute, helpPoints, onSelectRoute, onSelectHelp, className = "" }: { routes: MapRoute[]; selectedRoute: string; helpPoints: MapHelpPoint[]; onSelectRoute: (id:string)=>void; onSelectHelp: (id:string)=>void; className?:string }) {
 const container=useRef<HTMLDivElement>(null); const mapRef=useRef<MapLibreMap|null>(null);
 useEffect(()=>{ if(!container.current || mapRef.current) return; const map=new maplibregl.Map({ container:container.current, style:mapStyle, center:[72.835,19.057], zoom:13, attributionControl:false }); mapRef.current=map;
  map.on("load",()=>{ map.addSource("sp-routes",{type:"geojson",data:collection([])}); map.addSource("sp-help",{type:"geojson",data:{type:"FeatureCollection",features:[]}}); map.addLayer({id:"sp-route-alt",type:"line",source:"sp-routes",filter:["!=",["get","id"],selectedRoute],paint:{"line-color":"#65746d","line-width":5,"line-opacity":.65,"line-dasharray":[2,1.5]}}); map.addLayer({id:"sp-route-selected",type:"line",source:"sp-routes",filter:["==",["get","id"],selectedRoute],paint:{"line-color":"#16756c","line-width":8,"line-opacity":.95}}); map.addLayer({id:"sp-help-points",type:"circle",source:"sp-help",paint:{"circle-radius":7,"circle-color":"#fffefb","circle-stroke-color":"#16756c","circle-stroke-width":3}}); map.on("click","sp-route-alt",(e:MapLayerMouseEvent)=>{const id=e.features?.[0]?.properties?.id as string|undefined;if(id)onSelectRoute(id)}); map.on("click","sp-route-selected",(e:MapLayerMouseEvent)=>{const id=e.features?.[0]?.properties?.id as string|undefined;if(id)onSelectRoute(id)}); map.on("click","sp-help-points",(e:MapLayerMouseEvent)=>{const id=e.features?.[0]?.properties?.id as string|undefined;if(id)onSelectHelp(id)}); map.on("mouseenter","sp-route-alt",()=>map.getCanvas().style.cursor="pointer"); map.on("mouseleave","sp-route-alt",()=>map.getCanvas().style.cursor=""); }); return()=>{map.remove();mapRef.current=null}; },[onSelectHelp,onSelectRoute,selectedRoute]);
 useEffect(()=>{const map=mapRef.current;if(!map?.isStyleLoaded())return; const source=map.getSource("sp-routes") as GeoJSONSource|undefined; source?.setData(collection(routes.map(routeFeature))); const help=map.getSource("sp-help") as GeoJSONSource|undefined; help?.setData({type:"FeatureCollection",features:helpPoints.map(x=>({type:"Feature" as const,properties:{id:x.id},geometry:{type:"Point" as const,coordinates:x.coordinate}}))}); if(map.getLayer("sp-route-selected")){map.setFilter("sp-route-selected",["==",["get","id"],selectedRoute]);map.setFilter("sp-route-alt",["!=",["get","id"],selectedRoute]);} },[routes,helpPoints,selectedRoute]);
 return <div className={`relative overflow-hidden border border-[#bdc9c0] ${className}`}><div ref={container} className="h-full w-full" aria-label="Interactive route map"/><div className="absolute bottom-3 left-3 bg-[#fffefb] p-2 text-xs shadow-sm">Map · routes and help points</div><div className="absolute right-3 top-3 flex flex-col border border-[#d8ddd7] bg-[#fffefb]"><button onClick={()=>mapRef.current?.zoomIn()} className="h-10 w-10 text-lg" aria-label="Zoom in">+</button><button onClick={()=>mapRef.current?.zoomOut()} className="h-10 w-10 border-t border-[#d8ddd7] text-lg" aria-label="Zoom out">−</button><button onClick={()=>mapRef.current?.flyTo({center:[72.835,19.057],zoom:13})} className="h-10 w-10 border-t border-[#d8ddd7] text-xs" aria-label="Recenter map">◎</button></div></div>
}
