import type { RouteOption } from '../lib/types';

export const FIXTURE_ROUTES_BY_TIME: Record<'18:00' | '21:00' | '23:30', RouteOption[]> = {
  '18:00': [
    {
      id: 'route-1',
      name: 'Route 1',
      via: 'via Senapati Bapat Marg',
      durationMinutes: 21,
      distanceKm: 1.8,
      supportLevel: 'Stronger Contextual Support',
      confidence: 'High',
      freshness: 'Observed 10 mins ago',
      lightingEvidence: 'Well lit',
      footfallEvidence: 'Active evening commute & open storefronts',
      helpPointsCount: 4,
      cautionPointsCount: 0,
      whySummary: 'Active West Mumbai arterial corridor past Kabutarkhana & Dadar Market with continuous municipal LED lighting and active shopfronts.',
      segments: [
        {
          id: 'seg-1a',
          name: 'Segment A: Dadar West Station Plaza to Kabutarkhana',
          distanceKm: 0.9,
          durationMinutes: 10,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Active pedestrian traffic',
          evidenceObservedCount: 32,
          newestObservationTime: '5 mins ago',
          notes: ['Commercial shops illuminated', 'Busy transit junction & bus stop'],
        },
        {
          id: 'seg-1b',
          name: 'Segment B: Senapati Bapat Marg North to Matunga West',
          distanceKm: 0.9,
          durationMinutes: 11,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Active pedestrian traffic',
          evidenceObservedCount: 22,
          newestObservationTime: '10 mins ago',
          notes: ['Continuous municipal LED streetlamps', '24h Chemist open & lit'],
        },
      ],
    },
    {
      id: 'route-2',
      name: 'Route 2',
      via: 'via Hindu Colony & Lakhamsi Napoo Rd',
      durationMinutes: 25,
      distanceKm: 2.1,
      supportLevel: 'Mixed Context',
      confidence: 'High',
      freshness: 'Observed 25 mins ago',
      lightingEvidence: 'Mixed lighting',
      footfallEvidence: 'Moderate activity near Ruia College',
      helpPointsCount: 3,
      cautionPointsCount: 0,
      whySummary: 'Scenic tree-lined residential route through Hindu Colony past Podar and Ruia Colleges with steady evening student movement.',
      segments: [
        {
          id: 'seg-2a',
          name: 'Segment A: Dadar TT Circle to Hindu Colony Entrance',
          distanceKm: 1.0,
          durationMinutes: 12,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Active pedestrian traffic',
          evidenceObservedCount: 18,
          newestObservationTime: '20 mins ago',
          notes: ['24h Police desk nearby', 'Transit stop active'],
        },
        {
          id: 'seg-2b',
          name: 'Segment B: Lakhamsi Napoo Road (Ruia Pass) to Matunga Circle',
          distanceKm: 1.1,
          durationMinutes: 13,
          lightingStatus: 'Mixed streetlamps',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 14,
          newestObservationTime: '25 mins ago',
          notes: ['College campus perimeter lights', 'Tree-lined wide sidewalks'],
        },
      ],
    },
    {
      id: 'route-3',
      name: 'Route 3',
      via: 'via Dr B.A. Road',
      durationMinutes: 29,
      distanceKm: 2.4,
      supportLevel: 'Limited Data',
      confidence: 'Moderate',
      freshness: 'Observed 1 hour ago',
      lightingEvidence: 'Sparse lighting under flyover',
      footfallEvidence: 'Highway vehicular corridor',
      helpPointsCount: 1,
      cautionPointsCount: 1,
      whySummary: 'Major multi-lane arterial highway route past Chitra Cinema and Dadar TT Flyover with heavy vehicular traffic.',
      segments: [
        {
          id: 'seg-3a',
          name: 'Segment A: Dadar East Plaza past Chitra Cinema',
          distanceKm: 1.2,
          durationMinutes: 14,
          lightingStatus: 'Mixed streetlamps',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 8,
          newestObservationTime: '45 mins ago',
          notes: ['Chitra Cinema plaza illumination', 'High vehicular traffic'],
        },
        {
          id: 'seg-3b',
          name: 'Segment B: Flyover Underpass to Maheshwari Udyan',
          distanceKm: 1.2,
          durationMinutes: 15,
          lightingStatus: 'Sparse lighting',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 5,
          newestObservationTime: '1 hour ago',
          notes: ['Flyover underpass shadow zone'],
        },
      ],
    },
  ],

  '21:00': [
    {
      id: 'route-1',
      name: 'Route 1',
      via: 'via Senapati Bapat Marg',
      durationMinutes: 21,
      distanceKm: 1.8,
      supportLevel: 'Stronger Contextual Support',
      confidence: 'High',
      freshness: 'Observed 15 mins ago',
      lightingEvidence: 'Well lit',
      footfallEvidence: 'Moderate activity',
      helpPointsCount: 3,
      cautionPointsCount: 0,
      whySummary: 'At 9:00 PM, Senapati Bapat Marg maintains consistent streetlamp lighting and active 24h pharmacy desks near Kabutarkhana.',
      segments: [
        {
          id: 'seg-1a',
          name: 'Segment A: Dadar West Station Plaza to Kabutarkhana',
          distanceKm: 0.9,
          durationMinutes: 10,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 28,
          newestObservationTime: '10 mins ago',
          notes: ['Transit station active', 'Chemist shops open'],
        },
        {
          id: 'seg-1b',
          name: 'Segment B: Senapati Bapat Marg North to Matunga West',
          distanceKm: 0.9,
          durationMinutes: 11,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 19,
          newestObservationTime: '15 mins ago',
          notes: ['Smart LED lamps fully lit'],
        },
      ],
    },
    {
      id: 'route-2',
      name: 'Route 2',
      via: 'via Hindu Colony & Lakhamsi Napoo Rd',
      durationMinutes: 25,
      distanceKm: 2.1,
      supportLevel: 'Mixed Context',
      confidence: 'High',
      freshness: 'Observed 20 mins ago',
      lightingEvidence: 'Mixed lighting',
      footfallEvidence: 'Low activity near colleges',
      helpPointsCount: 2,
      cautionPointsCount: 0,
      whySummary: 'Quiet residential avenue past Ruia & Podar colleges; retail stores closed past 9:00 PM.',
      segments: [
        {
          id: 'seg-2a',
          name: 'Segment A: Dadar TT Circle to Hindu Colony Entrance',
          distanceKm: 1.0,
          durationMinutes: 12,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 15,
          newestObservationTime: '20 mins ago',
          notes: ['Police post desk staffed'],
        },
        {
          id: 'seg-2b',
          name: 'Segment B: Lakhamsi Napoo Road (Ruia Pass) to Matunga Circle',
          distanceKm: 1.1,
          durationMinutes: 13,
          lightingStatus: 'Mixed streetlamps',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 10,
          newestObservationTime: '25 mins ago',
          notes: ['Campus perimeter streetlamps active'],
        },
      ],
    },
    {
      id: 'route-3',
      name: 'Route 3',
      via: 'via Dr B.A. Road',
      durationMinutes: 29,
      distanceKm: 2.4,
      supportLevel: 'Limited Data',
      confidence: 'Moderate',
      freshness: 'Observed 1.5 hours ago',
      lightingEvidence: 'Sparse lighting',
      footfallEvidence: 'Low activity',
      helpPointsCount: 1,
      cautionPointsCount: 1,
      whySummary: 'Highway arterial route with fast vehicular movement; sparse pedestrian activity past flyover sections.',
      segments: [
        {
          id: 'seg-3a',
          name: 'Segment A: Dadar East Plaza past Chitra Cinema',
          distanceKm: 1.2,
          durationMinutes: 14,
          lightingStatus: 'Sparse lighting',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 5,
          newestObservationTime: '1 hour ago',
          notes: ['Chitra Cinema closed'],
        },
        {
          id: 'seg-3b',
          name: 'Segment B: Flyover Underpass to Maheshwari Udyan',
          distanceKm: 1.2,
          durationMinutes: 15,
          lightingStatus: 'Sparse lighting',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 3,
          newestObservationTime: '1.5 hours ago',
          notes: ['Dark foliage & flyover gaps between poles'],
        },
      ],
    },
  ],

  '23:30': [
    {
      id: 'route-1',
      name: 'Route 1',
      via: 'via Senapati Bapat Marg',
      durationMinutes: 21,
      distanceKm: 1.8,
      supportLevel: 'Stronger Contextual Support',
      confidence: 'High',
      freshness: 'Observed 5 mins ago',
      lightingEvidence: 'Well lit',
      footfallEvidence: 'Moderate activity',
      helpPointsCount: 3,
      cautionPointsCount: 0,
      whySummary: 'At 11:30 PM, Route 1 (via Senapati Bapat Marg) offers continuous 24h municipal LED lighting, active transit security, and 3 verified help points near Kabutarkhana.',
      segments: [
        {
          id: 'seg-1a',
          name: 'Segment A: Dadar West Station Plaza to Kabutarkhana',
          distanceKm: 0.9,
          durationMinutes: 10,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 26,
          newestObservationTime: '5 mins ago',
          notes: ['24h Nobel Chemist open & lit', 'Transit security active'],
        },
        {
          id: 'seg-1b',
          name: 'Segment B: Senapati Bapat Marg North to Matunga West',
          distanceKm: 0.9,
          durationMinutes: 11,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Moderate activity',
          evidenceObservedCount: 16,
          newestObservationTime: '10 mins ago',
          notes: ['Continuous LED smart lamps functional'],
        },
      ],
    },
    {
      id: 'route-2',
      name: 'Route 2',
      via: 'via Hindu Colony & Lakhamsi Napoo Rd',
      durationMinutes: 25,
      distanceKm: 2.1,
      supportLevel: 'Mixed Context',
      confidence: 'High',
      freshness: 'Observed 15 mins ago',
      lightingEvidence: 'Mixed lighting',
      footfallEvidence: 'Low activity',
      helpPointsCount: 2,
      cautionPointsCount: 0,
      whySummary: 'At 11:30 PM, Route 2 (via Hindu Colony & Lakhamsi Napoo Rd) exhibits mixed lighting where Ruia & Podar college campuses have closed for the night.',
      segments: [
        {
          id: 'seg-2a',
          name: 'Segment A: Dadar TT Circle to Hindu Colony Entrance',
          distanceKm: 1.0,
          durationMinutes: 12,
          lightingStatus: 'Well lit corridor',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 12,
          newestObservationTime: '15 mins ago',
          notes: ['Police post desk staffed'],
        },
        {
          id: 'seg-2b',
          name: 'Segment B: Lakhamsi Napoo Road (Ruia Pass) to Matunga Circle',
          distanceKm: 1.1,
          durationMinutes: 13,
          lightingStatus: 'Mixed streetlamps',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 8,
          newestObservationTime: '20 mins ago',
          notes: ['Quiet residential tree-lined lane'],
        },
      ],
    },
    {
      id: 'route-3',
      name: 'Route 3',
      via: 'via Dr B.A. Road',
      durationMinutes: 29,
      distanceKm: 2.4,
      supportLevel: 'Limited Data',
      confidence: 'Limited',
      freshness: 'Stale evidence (>7 days old)',
      isStale: true,
      lightingEvidence: 'Sparse lighting under flyover',
      footfallEvidence: 'Low activity',
      helpPointsCount: 1,
      cautionPointsCount: 2,
      whySummary: 'At 11:30 PM, Route 3 (via Dr B.A. Road) has sparse pedestrian footfall past flyover underpass segments. Telemetry is sparse.',
      segments: [
        {
          id: 'seg-3a',
          name: 'Segment A: Dadar East Plaza past Chitra Cinema',
          distanceKm: 1.2,
          durationMinutes: 14,
          lightingStatus: 'Sparse lighting',
          footfallStatus: 'Quiet / Low footfall',
          evidenceObservedCount: 2,
          newestObservationTime: '8 days ago',
          notes: ['Unlit underpass gaps'],
        },
        {
          id: 'seg-3b',
          name: 'Segment B: Flyover Underpass to Maheshwari Udyan',
          distanceKm: 1.2,
          durationMinutes: 15,
          lightingStatus: 'Unknown',
          footfallStatus: 'Unknown',
          evidenceObservedCount: 0,
          newestObservationTime: '14 days ago',
          notes: ['Limited telemetry'],
        },
      ],
    },
  ],
};

